require('dotenv').config();
const mongoose = require('mongoose');
const Movie = require('./models/Movie');

const MORE_MOVIES = [
  // ============ BOLLYWOOD ============
  {
    title: 'Download Animal (2023) BluRay Dual Audio (Hindi-English) 480p [600MB] | 720p [1.2GB] | 1080p [2.8GB]',
    cleanTitle: 'Animal',
    description: 'A son undergoes a remarkable transformation as the relationship with his father changes, and he becomes consumed by a need to protect his family at all costs. A violent, intense journey of love, betrayal, and obsession.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/hr9rjHkMPCGSBnJNRCVhOJnBxEN.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/lFwykSz3Ykj1Q3JXJURnGUTNf1o.jpg',
    releaseDate: new Date('2023-12-01'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Action', 'Crime', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 6.2,
    isTrending: true,
    isFeatured: true,
    tags: ['Bollywood', 'Action', 'Drama', 'Ranbir Kapoor'],
  },
  {
    title: 'Download Pathaan (2023) BluRay Dual Audio (Hindi-English) 480p [500MB] | 720p [1.1GB] | 1080p [2.5GB]',
    cleanTitle: 'Pathaan',
    description: 'An Indian spy takes on the leader of a group of mercenaries who have nefarious plans to destroy India through a series of deadly attacks.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/dGKzE3sCSlurDXjsi7aNcMrf7Jh.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/bGlJwj2PG2mMvg1VCfj4GPBEO7k.jpg',
    releaseDate: new Date('2023-01-25'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Thriller'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 6.4,
    isTrending: true,
    tags: ['Bollywood', 'Action', 'SRK'],
  },
  {
    title: 'Download Jawan (2023) WEB-DL Dual Audio (Hindi-English) 480p [550MB] | 720p [1GB] | 1080p [2.3GB]',
    cleanTitle: 'Jawan',
    description: 'A man is driven by a personal vendetta to rectify the wrongs in society, while keeping the element of mystery around him.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/jFMJ2vVIjczHnJhp48bIOQSZaMF.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/sOVbCAxRidpLJjdi2JEFaRqapuY.jpg',
    releaseDate: new Date('2023-09-07'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Action', 'Thriller', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.0,
    isTrending: true,
    isFeatured: true,
    tags: ['Bollywood', 'Action', 'SRK'],
  },
  {
    title: 'Download Dunki (2023) WEB-DL Hindi 480p [500MB] | 720p [1.1GB] | 1080p [2.4GB]',
    cleanTitle: 'Dunki',
    description: 'Four friends from a small Indian village embark on a quest to immigrate to England through the dangerous donkey flight route.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/jJvlxjiEGHEGNFNpamFypKLbBFb.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/gWLV8bCIr21JYBjnYVDsd0VjEFG.jpg',
    releaseDate: new Date('2023-12-21'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['Hindi'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Comedy', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 6.5,
    tags: ['Bollywood', 'Comedy', 'SRK'],
  },
  {
    title: 'Download Fighter (2024) WEB-DL Hindi 480p [550MB] | 720p [1.2GB] | 1080p [2.6GB]',
    cleanTitle: 'Fighter',
    description: 'Indian Air Force pilots undergo intense training and undertake a dangerous mission to protect their country from enemy attacks.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/yTJalWPVzmFCv5gUx3JVuhOvgh4.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7RCRTMaJDHLRQFdNDqOePuF3WDQN.jpg',
    releaseDate: new Date('2024-01-25'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Action', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 5.8,
    tags: ['Bollywood', 'Action', 'Hrithik'],
  },
  {
    title: 'Download 12th Fail (2023) WEB-DL Hindi 720p [900MB] | 1080p [2GB]',
    cleanTitle: '12th Fail',
    description: 'Based on a true story of Manoj Kumar Sharma who overcame the challenges of a flawed education system to become an IPS officer, inspiring millions.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/tBlBIEwvbX0VDsBqFCDRxPVYgdb.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/22tRfBwDGbhXIXkMSNEkJSLfnj.jpg',
    releaseDate: new Date('2023-10-27'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['Hindi'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Drama', 'Biography'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 9.2,
    isFeatured: true,
    tags: ['Bollywood', 'Drama', 'Inspirational'],
  },
  {
    title: 'Download Stree 2 (2024) WEB-DL Hindi 480p [500MB] | 720p [1GB] | 1080p [2.2GB]',
    cleanTitle: 'Stree 2',
    description: 'The residents of Chanderi face a new supernatural threat, and once again turn to the mysterious woman known as Stree for protection.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/6ggNaRsVAoLhfBpPfXFP2mWhKma.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kLjGCxNX0CKUDrGDc4y23WEcNYP.jpg',
    releaseDate: new Date('2024-08-15'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Horror', 'Comedy'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.1,
    isTrending: true,
    tags: ['Bollywood', 'Horror', 'Comedy'],
  },

  // ============ HOLLYWOOD ============
  {
    title: 'Download The Batman (2022) BluRay Dual Audio (Hindi-English) 1080p [2.5GB] | 2160p 4K [7GB]',
    cleanTitle: 'The Batman',
    description: 'When a sadistic serial killer begins murdering key political figures in Gotham, Batman is forced to investigate the hidden corruption plaguing the city.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/74xTEgt7R36Fpooo50r9T25onhq.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/b0PlSFdDwbyFAJlMeSrwxVBuXtD.jpg',
    releaseDate: new Date('2022-03-01'),
    releaseYear: 2022,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Crime', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.8,
    isTrending: true,
    tags: ['DC', 'Batman', 'Hollywood'],
  },
  {
    title: 'Download Spider-Man Across the Spider-Verse (2023) BluRay Dual Audio (Hindi-English) 1080p [2.1GB] | 2160p 4K [6GB]',
    cleanTitle: 'Spider-Man Across the Spider-Verse',
    description: 'Miles Morales catapults across the Multiverse where he encounters a team of Spider-People charged with protecting its very existence.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/8Vt6mWEReuy4Of61Lnj5Xj704m8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/4HodYYKEIsGOdinkGi2Ucz6X9i0.jpg',
    releaseDate: new Date('2023-05-31'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.7,
    isTrending: true,
    isFeatured: true,
    tags: ['Marvel', 'Spider-Man', 'Animation'],
  },
  {
    title: 'Download John Wick Chapter 4 (2023) BluRay Dual Audio (Hindi-English) 1080p [2.4GB] | 2160p 4K [7.5GB]',
    cleanTitle: 'John Wick Chapter 4',
    description: 'John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/vZloFAK7NmvMGKE7buoRSz2yGsJ.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7I6VUdPj6tQECNHdviJkUHD2u89.jpg',
    releaseDate: new Date('2023-03-22'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Thriller', 'Crime'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.7,
    isTrending: true,
    tags: ['Action', 'John Wick', 'Keanu Reeves'],
  },
  {
    title: 'Download Inception (2010) BluRay Dual Audio (Hindi-English) 1080p [2GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'Inception',
    description: 'A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/ljsZTbVsrQSqZgWeep2B1QiDKuh.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/8ZTVqvKDQ8emSGUEMjsS4yHAwrp.jpg',
    releaseDate: new Date('2010-07-15'),
    releaseYear: 2010,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Sci-Fi', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.8,
    isFeatured: true,
    tags: ['Nolan', 'Sci-Fi', 'Classic'],
  },
  {
    title: 'Download Interstellar (2014) BluRay Dual Audio (Hindi-English) 1080p [2.3GB] | 2160p 4K [8GB]',
    cleanTitle: 'Interstellar',
    description: 'When Earth becomes uninhabitable in the future, a farmer and ex-NASA pilot leads a team on a mission through a wormhole in search of a new home for humanity.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xJHokMbljvjADYdit5fK1DVfjko.jpg',
    releaseDate: new Date('2014-11-05'),
    releaseYear: 2014,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Adventure', 'Drama', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.7,
    isFeatured: true,
    tags: ['Nolan', 'Sci-Fi', 'Space'],
  },
  {
    title: 'Download The Dark Knight (2008) BluRay Dual Audio (Hindi-English) 1080p [2.2GB] | 2160p 4K [7GB]',
    cleanTitle: 'The Dark Knight',
    description: 'When the menace known as the Joker wreaks havoc and chaos on the people of Gotham, Batman must accept one of the greatest tests of his ability to fight injustice.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/qJ2tW6WMUDux911BTUgMe1nPpAI.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/nMKdUUepR0i5zn0y1T4CsSB5ez.jpg',
    releaseDate: new Date('2008-07-14'),
    releaseYear: 2008,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Crime', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 9.0,
    isFeatured: true,
    tags: ['DC', 'Batman', 'Joker', 'Classic'],
  },
  {
    title: 'Download Avengers Endgame (2019) BluRay Dual Audio (Hindi-English) 1080p [3GB] | 2160p 4K [9GB]',
    cleanTitle: 'Avengers Endgame',
    description: 'After the devastating events of Infinity War, the Avengers assemble once more to reverse the actions of Thanos and restore balance to the universe.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/or06FN3Dka5tukK1e9sl16pB3iy.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/7RyHsO4yDXtBv1zUU3mTpHeQ0d5.jpg',
    releaseDate: new Date('2019-04-24'),
    releaseYear: 2019,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.4,
    isTrending: true,
    isFeatured: true,
    tags: ['Marvel', 'Avengers', 'MCU'],
  },
  {
    title: 'Download Deadpool and Wolverine (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2.1GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'Deadpool and Wolverine',
    description: 'Deadpool is offered a place in the Marvel Cinematic Universe by the TVA but instead recruits a variant of Wolverine to save his universe from extinction.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/8cdWjvZQUExUUTzyp4t6EDMubfO.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/yDHYTfA3R0jFYba16jBB1ef8oIt.jpg',
    releaseDate: new Date('2024-07-24'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Action', 'Comedy', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.7,
    isTrending: true,
    tags: ['Marvel', 'Deadpool', 'Wolverine'],
  },
  {
    title: 'Download Godzilla x Kong The New Empire (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2GB] | 2160p 4K [6GB]',
    cleanTitle: 'Godzilla x Kong The New Empire',
    description: 'Two ancient titans, Godzilla and Kong, clash in an epic battle as humans unravel their intertwined origins and connection to Skull Island.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xRd1eJIDe7JHO5u4gtEYwGn5wtf.jpg',
    releaseDate: new Date('2024-03-27'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 6.4,
    tags: ['Monster', 'Action', 'Godzilla'],
  },
  {
    title: 'Download Inside Out 2 (2024) WEB-DL Dual Audio (Hindi-English) 720p [900MB] | 1080p [1.8GB]',
    cleanTitle: 'Inside Out 2',
    description: 'A sequel that follows Riley as a teenager with a new set of emotions vying for control, including Anxiety, Envy, and Embarrassment.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/vpnVM9B6NMmQpWeZvzLvDESb2QY.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xg27NrXi7VXCGUr7MN75UqLl6Vg.jpg',
    releaseDate: new Date('2024-06-11'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Animation', 'Comedy', 'Family'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.6,
    isTrending: true,
    tags: ['Pixar', 'Animation', 'Family'],
  },
  {
    title: 'Download Furiosa A Mad Max Saga (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2.4GB] | 2160p 4K [7GB]',
    cleanTitle: 'Furiosa A Mad Max Saga',
    description: 'The origin story of renegade warrior Furiosa before her encounter and target with Mad Max, showing how she fell into the hands of a great Biker Horde.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/iADOJ8Zymht2JPMoy3R7xceZprc.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/shrwC6U8Bkst9c9SnP8MNJg0PJi.jpg',
    releaseDate: new Date('2024-05-22'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.5,
    tags: ['Mad Max', 'Action', 'Post-Apocalyptic'],
  },
  {
    title: 'Download Alien Romulus (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2GB] | 2160p 4K [6GB]',
    cleanTitle: 'Alien Romulus',
    description: 'While scavenging the deep ends of a derelict space station, a group of young space colonists come face to face with the most terrifying life form in the universe.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/b33nnKl1GSFbao4l3fZDDqsMx0F.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9SSEUrSqhljBMzRe4aBTh17hYjd.jpg',
    releaseDate: new Date('2024-08-13'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.2,
    tags: ['Alien', 'Horror', 'Sci-Fi'],
  },

  // ============ ANIME ============
  {
    title: 'Download One Piece (1999-2024) WEB-DL 720p [500MB per Episode] | 1080p [1GB per Episode]',
    cleanTitle: 'One Piece',
    description: 'Monkey D. Luffy sets off on an adventure with his pirate crew in hopes of finding the greatest treasure in the world, known as One Piece.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/cMD9Ygz11zjJzAovURpO75Qg7rT.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/2rmK7mnchw9Xr3XdiTFSxTTLXqv.jpg',
    releaseDate: new Date('1999-10-20'),
    releaseYear: 1999,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 9.0,
    isTrending: true,
    isFeatured: true,
    tags: ['Anime', 'One Piece', 'Luffy'],
  },
  {
    title: 'Download Dragon Ball Super (2015-2018) WEB-DL 720p [400MB per Episode] | 1080p [900MB per Episode]',
    cleanTitle: 'Dragon Ball Super',
    description: 'With Earth at peace after the defeat of Majin Buu, Goku and friends face new challenges from powerful gods and warriors from other universes.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/1yBFnXEwIW6UrSI0es99wM9VFZL.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/fj8aA0dGkS2F2VJaXQCvB1oyBdX.jpg',
    releaseDate: new Date('2015-07-05'),
    releaseYear: 2015,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English', 'Hindi'],
    type: 'anime',
    ottPlatform: 'other',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.4,
    isTrending: true,
    tags: ['Anime', 'Dragon Ball', 'Goku'],
  },
  {
    title: 'Download My Hero Academia Season 7 (2024) WEB-DL 720p [500MB] | 1080p [1.1GB]',
    cleanTitle: 'My Hero Academia Season 7',
    description: 'In a world where most people have superpowers, Izuku Midoriya dreams of being a hero despite being born without a quirk.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/ivOLM47yJt90P19RH1NvJbAJbZ1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9TAhRShQFfRyBbVWuigqFYnF33e.jpg',
    releaseDate: new Date('2024-05-04'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.3,
    tags: ['Anime', 'MHA', 'Superhero'],
  },
  {
    title: 'Download Solo Leveling (2024) WEB-DL 720p [450MB] | 1080p [1GB]',
    cleanTitle: 'Solo Leveling',
    description: 'In a world where hunters with magical abilities must battle deadly monsters to protect the human race, Sung Jinwoo, the weakest hunter, begins a mysterious quest to become the strongest.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/geCRueV3ElhRTr0xtJuEWJt6dJ1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/hH3nz0AOL47AR0NKQRXDWE54Hx9.jpg',
    releaseDate: new Date('2024-01-06'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Fantasy'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.3,
    isTrending: true,
    isFeatured: true,
    tags: ['Anime', 'Solo Leveling', 'Fantasy'],
  },
  {
    title: 'Download Death Note (2006) Complete Series 720p [3GB] | 1080p [6.5GB]',
    cleanTitle: 'Death Note',
    description: 'An intelligent high school student goes on a secret crusade to eliminate criminals from the world after discovering a notebook capable of killing anyone whose name is written into it.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/iigTJJSLacCBxwERkEj1qnGtgSY.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/A2t6gC3NQf9YkBIdCMhQcRRDBjP.jpg',
    releaseDate: new Date('2006-10-03'),
    releaseYear: 2006,
    source: 'BluRay',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Crime', 'Mystery'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 9.0,
    isFeatured: true,
    tags: ['Anime', 'Death Note', 'Psychological'],
  },
  {
    title: 'Download Chainsaw Man (2022) WEB-DL 720p [400MB] | 1080p [900MB]',
    cleanTitle: 'Chainsaw Man',
    description: 'Denji is a teenage boy living under harsh conditions to pay off his dead father\'s debt. His pet, a devil named Pochita, merges with him to become Chainsaw Man.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/yVtx7Xn9UxNJqvG2BkvhCcmed9S.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/5VKEguhJBWoE9Bo2nbEBBNxIGkS.jpg',
    releaseDate: new Date('2022-10-11'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Horror'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.5,
    isTrending: true,
    tags: ['Anime', 'Chainsaw Man', 'Dark'],
  },
  {
    title: 'Download Fullmetal Alchemist Brotherhood (2009) Complete Series 720p [4GB] | 1080p [8GB]',
    cleanTitle: 'Fullmetal Alchemist Brotherhood',
    description: 'Two brothers search for a Philosopher\'s Stone after an pointless attempt at alchemy to restore their bodies goes wrong.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/1E5baAaEse26fej7uHcjOgEERB2.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/q4PCAO1KzWZqYkZdeahOd8KAI7m.jpg',
    releaseDate: new Date('2009-04-05'),
    releaseYear: 2009,
    source: 'BluRay',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 9.1,
    isFeatured: true,
    tags: ['Anime', 'FMA', 'Classic'],
  },

  // ============ K-DRAMA ============
  {
    title: 'Download Crash Landing on You (2019) Korean Drama WEB-DL 720p [700MB] | 1080p [1.5GB]',
    cleanTitle: 'Crash Landing on You',
    description: 'A South Korean heiress accidentally paraglides into North Korea and falls in love with a North Korean army officer who helps hide her.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/aFqNlGvR3wct55NwmCphv9y14vX.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/d6E6yVjCaBjOK7WMkHxDyUqppoc.jpg',
    releaseDate: new Date('2019-12-14'),
    releaseYear: 2019,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Romance', 'Comedy'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.7,
    isTrending: true,
    isFeatured: true,
    tags: ['K-Drama', 'Romance', 'Netflix'],
  },
  {
    title: 'Download All of Us Are Dead (2022) Korean Drama WEB-DL 720p [750MB] | 1080p [1.6GB]',
    cleanTitle: 'All of Us Are Dead',
    description: 'A zombie virus outbreak at a high school traps students inside, where they must fight to survive while waiting for rescue.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/pTEFqAjLd5YGUFk5pMFBJFGWOuP.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/qFYkEJfkRBhPnFjXTKmMjHrI2pz.jpg',
    releaseDate: new Date('2022-01-28'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Horror', 'Drama', 'Thriller'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.5,
    isTrending: true,
    tags: ['K-Drama', 'Zombie', 'Horror'],
  },
  {
    title: 'Download Vincenzo (2021) Korean Drama WEB-DL 720p [700MB] | 1080p [1.5GB]',
    cleanTitle: 'Vincenzo',
    description: 'An Italian-Korean mafia lawyer returns to South Korea and fights against villainous conglomerates using his cunning and devious methods.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/dvXJgEBPlJV0TBn1AIkjfn1OQEv.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/jKD7Srq6lKiKNa2CnBHiSUp3gFA.jpg',
    releaseDate: new Date('2021-02-20'),
    releaseYear: 2021,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Crime', 'Drama', 'Comedy'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.4,
    tags: ['K-Drama', 'Crime', 'Comedy'],
  },
  {
    title: 'Download Extraordinary Attorney Woo (2022) Korean Drama WEB-DL 720p [700MB] | 1080p [1.5GB]',
    cleanTitle: 'Extraordinary Attorney Woo',
    description: 'A brilliant attorney with autism spectrum disorder joins a major law firm where she handles various legal cases with her exceptional memory skills.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/wVIdPEjRorBxj74m0EOIG5lAAI9.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/pFfnNqhSeMz0cqJzouuPEiM6o5U.jpg',
    releaseDate: new Date('2022-06-29'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Comedy'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.6,
    tags: ['K-Drama', 'Legal', 'Drama'],
  },
  {
    title: 'Download The Glory (2022) Korean Drama WEB-DL 720p [700MB] | 1080p [1.5GB]',
    cleanTitle: 'The Glory',
    description: 'A woman who was brutally bullied in school devotes her life to meticulously plotting the perfect revenge against her tormentors years later.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/kJnoGkDHMmVEEzfMNRAKiFLgjVn.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9zcbqSxbsOQVv3WUAxehSm8S4Bi.jpg',
    releaseDate: new Date('2022-12-30'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Thriller'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.1,
    isTrending: true,
    tags: ['K-Drama', 'Revenge', 'Thriller'],
  },

  // ============ SERIES ============
  {
    title: 'Download Breaking Bad Complete Series (2008-2013) BluRay 1080p [2GB per Season] | 2160p 4K [5GB per Season]',
    cleanTitle: 'Breaking Bad Complete Series',
    description: 'A chemistry teacher diagnosed with inoperable lung cancer turns to manufacturing and selling methamphetamine to secure his family\'s future.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/ztkUQFLlC19CCMYHW73GMzYN0X.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/tsRy63Mu5cu8etL1X7ZLyf7UP1M.jpg',
    releaseDate: new Date('2008-01-20'),
    releaseYear: 2008,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Crime', 'Drama', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 9.5,
    isFeatured: true,
    tags: ['Series', 'Crime', 'Classic'],
  },
  {
    title: 'Download Money Heist Complete Series (2017-2021) WEB-DL 720p [800MB per Season] | 1080p [1.8GB per Season]',
    cleanTitle: 'Money Heist',
    description: 'An unusual group of robbers attempt the biggest heist in Spanish history — stealing billions from the Royal Mint of Spain under the direction of the mysterious Professor.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/reEMJA1uzscCbkpeRJeTT2bjqUp.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/xGexTKCJDkl12dTW4YCBDXWb1AD.jpg',
    releaseDate: new Date('2017-05-02'),
    releaseYear: 2017,
    source: 'WEB-DL',
    audioLanguages: ['Spanish', 'English', 'Hindi'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Crime', 'Drama', 'Thriller'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.2,
    isTrending: true,
    tags: ['Series', 'Heist', 'Spanish'],
  },
  {
    title: 'Download Wednesday Season 1 (2022) WEB-DL 720p [800MB] | 1080p [1.7GB]',
    cleanTitle: 'Wednesday Season 1',
    description: 'Wednesday Addams investigates a monster killing spree at Nevermore Academy while navigating new and very tangled relationships.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/9PFonBhy4cQy7Jz20NpMygczOkv.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/iHSwvRVsNBTngVvXEB6Ttl1jLb3.jpg',
    releaseDate: new Date('2022-11-23'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Comedy', 'Mystery', 'Fantasy'],
    qualities: ['720p', '1080p'],
    downloadLinks: [],
    imdbRating: 8.1,
    isTrending: true,
    tags: ['Series', 'Wednesday', 'Netflix'],
  },
  {
    title: 'Download Stranger Things Season 4 (2022) WEB-DL 1080p [2.5GB] | 2160p 4K [7GB]',
    cleanTitle: 'Stranger Things Season 4',
    description: 'The gang faces a new terrifying supernatural threat from the Upside Down as they navigate high school and the mystery surrounding Vecna.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/49WJfeN0moxb9IPfGn8AIqMGskD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/56v2KjBlYj3Yw6fGC2r3ibaFsXa.jpg',
    releaseDate: new Date('2022-05-27'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Fantasy', 'Horror'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.7,
    isTrending: true,
    isFeatured: true,
    tags: ['Series', 'Stranger Things', 'Horror'],
  },
  {
    title: 'Download The Last of Us Season 1 (2023) WEB-DL 1080p [2.2GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'The Last of Us Season 1',
    description: 'In a post-apocalyptic world ravaged by a fungal infection, a hardened survivor is hired to smuggle a teenage girl out of an oppressive quarantine zone.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/uKvVjHNqB5VmOrdxqAt2F7J78ED.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/uDgy6hyPd82kOHh6I95FLtM8gZp.jpg',
    releaseDate: new Date('2023-01-15'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'other',
    genres: ['Drama', 'Action', 'Adventure'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.8,
    isFeatured: true,
    tags: ['Series', 'HBO', 'Post-Apocalyptic'],
  },
  {
    title: 'Download House of the Dragon Season 2 (2024) WEB-DL 1080p [2.3GB] | 2160p 4K [7GB]',
    cleanTitle: 'House of the Dragon Season 2',
    description: 'The Targaryen civil war intensifies as both sides of the conflict escalate their struggle for the Iron Throne in the Dance of the Dragons.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/t9XkeE7HzOsdQcDDDapDYh8Rrmt.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/etj8E2o0Bud0HkONVQPjyCkIvpv.jpg',
    releaseDate: new Date('2024-06-16'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'other',
    genres: ['Drama', 'Fantasy', 'Action'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.0,
    isTrending: true,
    tags: ['Series', 'GOT', 'HBO', 'Dragons'],
  },

  // ============ SOUTH INDIAN ============
  {
    title: 'Download RRR (2022) BluRay Dual Audio (Hindi-Telugu) 480p [600MB] | 720p [1.2GB] | 1080p [2.8GB]',
    cleanTitle: 'RRR',
    description: 'A fictional story about two legendary revolutionaries and their journey away from home before they began fighting for their country.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/nEufeZYoEev50POHbkNKuJtYPEg.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/iWAlBIw8kDOYqGDG3cXbGti2unj.jpg',
    releaseDate: new Date('2022-03-25'),
    releaseYear: 2022,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'Telugu', 'English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Action', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.8,
    isTrending: true,
    isFeatured: true,
    tags: ['South Indian', 'Tollywood', 'Action'],
  },
  {
    title: 'Download KGF Chapter 2 (2022) BluRay Dual Audio (Hindi-Kannada) 480p [550MB] | 720p [1.1GB] | 1080p [2.5GB]',
    cleanTitle: 'KGF Chapter 2',
    description: 'Rocky takes over the Kolar Gold Fields empire and must deal with the growing threats from rival gangs, politicians, and the government.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/qJMEBSiLRJmSBENBEzZfNl7YiCf.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/dsmWIkGE5ydDMXhX2iD1fLEL0Lt.jpg',
    releaseDate: new Date('2022-04-14'),
    releaseYear: 2022,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'Kannada'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Drama', 'Thriller'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 7.4,
    isTrending: true,
    tags: ['South Indian', 'Kannada', 'Action'],
  },
  {
    title: 'Download Pushpa 2 The Rule (2024) WEB-DL Dual Audio (Hindi-Telugu) 480p [600MB] | 720p [1.3GB] | 1080p [2.8GB]',
    cleanTitle: 'Pushpa 2 The Rule',
    description: 'Pushpa Raj continues his rise in the world of red sandalwood smuggling, facing bigger threats and more powerful enemies than ever before.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/qGBUFbgkHNOuBdoGvI4hBePFaHV.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9t3fSqwcwZhJYVjMuNSt3hb3mI3.jpg',
    releaseDate: new Date('2024-12-05'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'Telugu'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Drama', 'Thriller'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [],
    imdbRating: 6.8,
    isTrending: true,
    isFeatured: true,
    tags: ['South Indian', 'Tollywood', 'Pushpa'],
  },
  {
    title: 'Download Kalki 2898 AD (2024) WEB-DL Dual Audio (Hindi-Telugu) 1080p [2.5GB] | 2160p 4K [7GB]',
    cleanTitle: 'Kalki 2898 AD',
    description: 'Set in a dystopian future, this epic sci-fi adventure draws from Hindu mythology as warriors unite against a powerful villain threatening humanity.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/mINJaa34MtknCYl5AjtNJzWj8cD.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/k0JzHFzqfZgONGNJOcwDcWNmJsR.jpg',
    releaseDate: new Date('2024-06-27'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'Telugu'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Action', 'Sci-Fi', 'Adventure'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 6.7,
    isTrending: true,
    tags: ['South Indian', 'Sci-Fi', 'Prabhas'],
  },

  // ============ MORE HOLLYWOOD ============
  {
    title: 'Download The Shawshank Redemption (1994) BluRay 1080p [2GB] | 2160p 4K [6GB]',
    cleanTitle: 'The Shawshank Redemption',
    description: 'A banker convicted of uxoricide forms a friendship over a quarter century with a hardened convict, while maintaining his innocence and dreaming of freedom.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/9cqNcoGLjRzpGacixPxJHVPJqPO.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/kXfqcdQKsToO0OUXHcrrNCHDBzO.jpg',
    releaseDate: new Date('1994-09-23'),
    releaseYear: 1994,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 9.3,
    isFeatured: true,
    tags: ['Classic', 'Drama', 'Prison'],
  },
  {
    title: 'Download Fight Club (1999) BluRay 1080p [2GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'Fight Club',
    description: 'An insomniac office worker and a devil-may-care soap maker form an underground fight club that evolves into much more.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/pB8BM7pdSp6B6Ih7QI4S2t0POvR.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/52AfXWnXi1Hy9QzDk8TjYI0VCEQ.jpg',
    releaseDate: new Date('1999-10-15'),
    releaseYear: 1999,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Drama', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 8.8,
    isFeatured: true,
    tags: ['Classic', 'Thriller', 'Brad Pitt'],
  },
  {
    title: 'Download Gladiator II (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2.3GB] | 2160p 4K [7GB]',
    cleanTitle: 'Gladiator II',
    description: 'Years after witnessing the death of Maximus at the hands of his uncle, Lucius is forced to enter the Colosseum and must look to his past to fight for his future.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/2cxhvwyEwRlysAmRH4iodkvo0z5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/euYIwmwkmz95mnXvufEoKeN2Ihl.jpg',
    releaseDate: new Date('2024-11-13'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Adventure', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 6.9,
    isTrending: true,
    tags: ['Gladiator', 'Action', 'Epic'],
  },
  {
    title: 'Download Joker Folie a Deux (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2.1GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'Joker Folie a Deux',
    description: 'Arthur Fleck is institutionalized at Arkham awaiting trial for his crimes as Joker. While struggling with his dual identity, Arthur falls in love.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/aciP8Km0waTLXEYf5ybFK5CSUxl.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/uGmfSHZBkkEho6gFgnOH2zcLFCM.jpg',
    releaseDate: new Date('2024-10-01'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Drama', 'Crime', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 5.2,
    tags: ['DC', 'Joker', 'Drama'],
  },
  {
    title: 'Download Wicked (2024) WEB-DL Dual Audio (Hindi-English) 1080p [2.2GB] | 2160p 4K [6.8GB]',
    cleanTitle: 'Wicked',
    description: 'The untold story of the witches of Oz — Elphaba, a misunderstood green-skinned woman, and Glinda, a popular and ambitious socialite.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/c5Tqxeo1UpBvnAc3csUm7j3hlQl.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/uVlUu174iiKhsUGqnOSy46eIIMU.jpg',
    releaseDate: new Date('2024-11-20'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'other',
    genres: ['Fantasy', 'Musical', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 7.6,
    isTrending: true,
    tags: ['Musical', 'Fantasy', 'Wicked'],
  },
  {
    title: 'Download A Quiet Place Day One (2024) WEB-DL Dual Audio (Hindi-English) 1080p [1.8GB] | 2160p 4K [5.5GB]',
    cleanTitle: 'A Quiet Place Day One',
    description: 'Experience the day the world went quiet. When deadly creatures that hunt by sound arrive on Earth, a woman must find strength to survive in a terrified city.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/hU42CRk14JuPEdqZG3AWmagiPAP.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/9mMhNhCcMlZOBUP3oN1KOsUSEzz.jpg',
    releaseDate: new Date('2024-06-26'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Horror', 'Sci-Fi', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 6.7,
    tags: ['Horror', 'Sci-Fi', 'Quiet Place'],
  },

  // ============ DOCUMENTARY ============
  {
    title: 'Download Our Planet Season 2 (2023) WEB-DL 1080p [1.5GB] | 2160p 4K [4GB]',
    cleanTitle: 'Our Planet Season 2',
    description: 'Explore the beauty and fragility of natural world, from the depths of the oceans to the most remote forests, and witness how climate change affects every living creature.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/8HYVFo3OowVlaXqAd9R5v1rSEnM.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/jdQEsDQJLtHZiQ7TDzg97fJXJGq.jpg',
    releaseDate: new Date('2023-06-14'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'documentary',
    ottPlatform: 'netflix',
    genres: ['Documentary', 'Nature'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 9.3,
    tags: ['Documentary', 'Nature', 'Netflix'],
  },
  {
    title: 'Download Planet Earth III (2023) BluRay 1080p [2GB] | 2160p 4K [6GB]',
    cleanTitle: 'Planet Earth III',
    description: 'David Attenborough narrates this stunning documentary series exploring the most spectacular landscapes and wildlife across the planet.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/plsY6BPiITafasb2gEhCxWbqK16.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/lTB4e95xfPayarBcSBBbNVcQLDz.jpg',
    releaseDate: new Date('2023-10-22'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'documentary',
    ottPlatform: 'other',
    genres: ['Documentary', 'Nature'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [],
    imdbRating: 9.5,
    isFeatured: true,
    tags: ['Documentary', 'BBC', 'Nature'],
  },
];

function generateSlug(cleanTitle) {
  return cleanTitle
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-');
}

async function addMovies() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    const existingCount = await Movie.countDocuments();
    console.log(`Existing movies in DB: ${existingCount}`);

    let added = 0;
    let skipped = 0;

    for (const movie of MORE_MOVIES) {
      const slug = generateSlug(movie.cleanTitle);
      const exists = await Movie.findOne({ slug });
      if (exists) {
        console.log(`  Skipped (exists): ${movie.cleanTitle}`);
        skipped++;
        continue;
      }

      await Movie.create({ ...movie, slug });
      console.log(`  Added: ${movie.cleanTitle}`);
      added++;
    }

    const totalCount = await Movie.countDocuments();
    console.log(`\n=== Summary ===`);
    console.log(`Added: ${added}`);
    console.log(`Skipped: ${skipped}`);
    console.log(`Total movies in DB: ${totalCount}`);

    process.exit(0);
  } catch (error) {
    console.error('Error:', error.message);
    process.exit(1);
  }
}

addMovies();
