require('dotenv').config();
const mongoose = require('mongoose');
const Movie = require('./models/Movie');
const Admin = require('./models/Admin');
const SiteLink = require('./models/SiteLink');

const SAMPLE_MOVIES = [
  {
    title: 'Download Peaky Blinders: The Immortal Man (2026) WEB-DL Dual Audio (Hindi-English) 480p [550MB] | 720p [900MB] | 1080p [1.8GB]',
    cleanTitle: 'Peaky Blinders The Immortal Man',
    description: 'The Peaky Blinders return for their final chapter in this gripping conclusion to the acclaimed series.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example1.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example1.jpg',
    releaseDate: new Date('2026-03-15'),
    releaseYear: 2026,
    source: 'WEB-DL',
    audioLanguages: ['Hindi', 'English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Crime', 'Drama'],
    qualities: ['480p', '720p', '1080p'],
    downloadLinks: [
      { quality: '480p', size: '550MB', label: '480p [550MB]', url: 'https://example.com/dl1' },
      { quality: '720p', size: '900MB', label: '720p [900MB]', url: 'https://example.com/dl2' },
      { quality: '1080p', size: '1.8GB', label: '1080p [1.8GB]', url: 'https://example.com/dl3' },
    ],
    imdbRating: 8.5,
    isTrending: true,
    isFeatured: true,
    tags: ['Crime', 'Drama', 'Series'],
  },
  {
    title: 'Download Dune: Part Two (2026) BluRay Dual Audio (Hindi-English) 1080p [2.5GB] | 2160p 4K [8GB]',
    cleanTitle: 'Dune Part Two',
    description: 'Paul Atreides travels to the dangerous planet Arrakis to ensure the future of his family and people.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example2.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example2.jpg',
    releaseDate: new Date('2024-02-28'),
    releaseYear: 2024,
    source: 'BluRay',
    audioLanguages: ['Hindi', 'English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Action', 'Adventure', 'Sci-Fi'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2.5GB', label: '1080p [2.5GB]', url: 'https://example.com/dl4' },
      { quality: '2160p', size: '8GB', label: '2160p 4K [8GB]', url: 'https://example.com/dl5' },
    ],
    imdbRating: 8.2,
    isTrending: true,
    tags: ['Sci-Fi', 'Action', 'Movie'],
  },
  {
    title: 'Download Jujutsu Kaisen Season 2 (2023) WEB-DL 720p [600MB per Episode] | 1080p [1.2GB per Episode]',
    cleanTitle: 'Jujutsu Kaisen Season 2',
    description: 'Yuji Itadori and the jujutsu sorcerers continue their battle against cursed spirits in this thrilling anime series.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example3.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example3.jpg',
    releaseDate: new Date('2023-07-01'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '600MB', label: '720p [600MB]', url: 'https://example.com/dl6' },
      { quality: '1080p', size: '1.2GB', label: '1080p [1.2GB]', url: 'https://example.com/dl7' },
    ],
    imdbRating: 8.7,
    isTrending: true,
    tags: ['Anime', 'Action'],
  },
  {
    title: 'Download Goblin (2016) Korean Drama WEB-DL 720p [700MB] | 1080p [1.5GB]',
    cleanTitle: 'Goblin',
    description: 'A goblin cursed to live forever searches for a human to pull out the sword from his chest.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example4.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example4.jpg',
    releaseDate: new Date('2016-12-02'),
    releaseYear: 2016,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Fantasy', 'Romance'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '700MB', label: '720p [700MB]', url: 'https://example.com/dl8' },
      { quality: '1080p', size: '1.5GB', label: '1080p [1.5GB]', url: 'https://example.com/dl9' },
    ],
    imdbRating: 8.8,
    isTrending: true,
    tags: ['K-Drama', 'Fantasy', 'Romance'],
  },
  {
    title: 'Download The Crown Season 5 (2022) WEB-DL 1080p [2GB] | 2160p 4K [6GB]',
    cleanTitle: 'The Crown Season 5',
    description: 'Explore the reign of Queen Elizabeth II and the British royal family through the decades.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example5.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example5.jpg',
    releaseDate: new Date('2022-11-09'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2GB', label: '1080p [2GB]', url: 'https://example.com/dl10' },
      { quality: '2160p', size: '6GB', label: '2160p 4K [6GB]', url: 'https://example.com/dl11' },
    ],
    imdbRating: 8.0,
    tags: ['Crown', 'Drama'],
  },
  {
    title: 'Download Naruto Shippuden Complete Series (2007-2017) 720p [2.5GB] per Arc | 1080p [5GB]',
    cleanTitle: 'Naruto Shippuden Complete Series',
    description: 'The ultimate ninja adventure continues as Naruto and friends battle powerful enemies.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example6.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example6.jpg',
    releaseDate: new Date('2007-02-15'),
    releaseYear: 2007,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English', 'Hindi'],
    type: 'anime',
    ottPlatform: 'other',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '2.5GB', label: '720p [2.5GB]', url: 'https://example.com/dl12' },
      { quality: '1080p', size: '5GB', label: '1080p [5GB]', url: 'https://example.com/dl13' },
    ],
    imdbRating: 8.9,
    isTrending: true,
    tags: ['Anime', 'Naruto'],
  },
  {
    title: 'Download Damsel (2024) Netflix Original WEB-DL 1080p [1.8GB] | 2160p 4K [5.5GB]',
    cleanTitle: 'Damsel',
    description: 'A strong-willed young woman must navigate a dangerous castle to save her kingdom.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example7.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example7.jpg',
    releaseDate: new Date('2024-03-08'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '1.8GB', label: '1080p [1.8GB]', url: 'https://example.com/dl14' },
      { quality: '2160p', size: '5.5GB', label: '2160p 4K [5.5GB]', url: 'https://example.com/dl15' },
    ],
    imdbRating: 7.3,
    isFeatured: true,
    tags: ['Netflix', 'Fantasy'],
  },
  {
    title: 'Download Demon Slayer Kimetsu no Yaiba (2019) 720p [800MB] | 1080p [1.6GB] | 2160p 4K [4GB]',
    cleanTitle: 'Demon Slayer Kimetsu no Yaiba',
    description: 'A young swordsman seeks to become a Demon Slayer to save his sister from a terrible curse.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example8.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example8.jpg',
    releaseDate: new Date('2019-04-06'),
    releaseYear: 2019,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p', '2160p'],
    downloadLinks: [
      { quality: '720p', size: '800MB', label: '720p [800MB]', url: 'https://example.com/dl16' },
      { quality: '1080p', size: '1.6GB', label: '1080p [1.6GB]', url: 'https://example.com/dl17' },
      { quality: '2160p', size: '4GB', label: '2160p 4K [4GB]', url: 'https://example.com/dl18' },
    ],
    imdbRating: 8.8,
    isTrending: true,
    tags: ['Anime', 'Action'],
  },
  {
    title: 'Download The Witcher Season 3 (2023) WEB-DL 1080p [2.2GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'The Witcher Season 3',
    description: 'Geralt of Rivia embarks on a complex quest filled with danger and destiny.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example9.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example9.jpg',
    releaseDate: new Date('2023-06-29'),
    releaseYear: 2023,
    source: 'WEB-DL',
    audioLanguages: ['English', 'Polish'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Fantasy', 'Adventure', 'Drama'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2.2GB', label: '1080p [2.2GB]', url: 'https://example.com/dl19' },
      { quality: '2160p', size: '6.5GB', label: '2160p 4K [6.5GB]', url: 'https://example.com/dl20' },
    ],
    imdbRating: 7.8,
    isTrending: true,
    tags: ['Witcher', 'Fantasy'],
  },
  {
    title: 'Download Oppenheimer (2023) BluRay 1080p [2.2GB] | 2160p 4K [7GB]',
    cleanTitle: 'Oppenheimer',
    description: 'The story of J. Robert Oppenheimer and the development of the atomic bomb.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example10.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example10.jpg',
    releaseDate: new Date('2023-07-21'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Biography', 'Drama', 'History'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2.2GB', label: '1080p [2.2GB]', url: 'https://example.com/dl21' },
      { quality: '2160p', size: '7GB', label: '2160p 4K [7GB]', url: 'https://example.com/dl22' },
    ],
    imdbRating: 8.1,
    isTrending: true,
    isFeatured: true,
    tags: ['Historical', 'Drama'],
  },
  {
    title: 'Download Squid Game Season 2 (2024) WEB-DL Korean 1080p [1.9GB] | 2160p 4K [5.8GB]',
    cleanTitle: 'Squid Game Season 2',
    description: 'The deadly games return as new players enter the competition.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example11.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example11.jpg',
    releaseDate: new Date('2024-12-26'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'series',
    ottPlatform: 'netflix',
    genres: ['Drama', 'Thriller'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '1.9GB', label: '1080p [1.9GB]', url: 'https://example.com/dl23' },
      { quality: '2160p', size: '5.8GB', label: '2160p 4K [5.8GB]', url: 'https://example.com/dl24' },
    ],
    imdbRating: 8.0,
    isTrending: true,
    tags: ['K-Drama', 'Thriller'],
  },
  {
    title: 'Download Killers of the Flower Moon (2023) BluRay 1080p [2.3GB] | 2160p 4K [7.2GB]',
    cleanTitle: 'Killers of the Flower Moon',
    description: 'A murder conspiracy involving Native American Osage people in 1920s Oklahoma.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example12.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example12.jpg',
    releaseDate: new Date('2023-10-27'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'amazon',
    genres: ['Crime', 'Drama', 'History'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2.3GB', label: '1080p [2.3GB]', url: 'https://example.com/dl25' },
      { quality: '2160p', size: '7.2GB', label: '2160p 4K [7.2GB]', url: 'https://example.com/dl26' },
    ],
    imdbRating: 8.2,
    isFeatured: true,
    tags: ['Historical', 'Crime'],
  },
  {
    title: 'Download Attack on Titan Complete Series (2013-2023) 720p [3GB] | 1080p [6GB]',
    cleanTitle: 'Attack on Titan Complete Series',
    description: 'Humanity fights for survival against giant humanoid creatures in a walled city.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example13.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example13.jpg',
    releaseDate: new Date('2013-04-07'),
    releaseYear: 2013,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Action', 'Adventure'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '3GB', label: '720p [3GB]', url: 'https://example.com/dl27' },
      { quality: '1080p', size: '6GB', label: '1080p [6GB]', url: 'https://example.com/dl28' },
    ],
    imdbRating: 8.9,
    isTrending: true,
    tags: ['Anime', 'Action'],
  },
  {
    title: 'Download Descendants of the Sun (2016) Korean Drama WEB-DL 720p [750MB] | 1080p [1.6GB]',
    cleanTitle: 'Descendants of the Sun',
    description: 'A romance between a soldier and a surgeon unfolds amid war and danger.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example14.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example14.jpg',
    releaseDate: new Date('2016-02-24'),
    releaseYear: 2016,
    source: 'WEB-DL',
    audioLanguages: ['Korean', 'English'],
    type: 'kdrama',
    ottPlatform: 'other',
    genres: ['Drama', 'Romance', 'Action'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '750MB', label: '720p [750MB]', url: 'https://example.com/dl29' },
      { quality: '1080p', size: '1.6GB', label: '1080p [1.6GB]', url: 'https://example.com/dl30' },
    ],
    imdbRating: 8.5,
    tags: ['K-Drama', 'Romance'],
  },
  {
    title: 'Download Barbie (2023) BluRay 1080p [2GB] | 2160p 4K [6.5GB]',
    cleanTitle: 'Barbie',
    description: 'A doll comes to life and embarks on an adventure to find her place in the world.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example15.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example15.jpg',
    releaseDate: new Date('2023-07-21'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'netflix',
    genres: ['Comedy', 'Fantasy', 'Adventure'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '2GB', label: '1080p [2GB]', url: 'https://example.com/dl31' },
      { quality: '2160p', size: '6.5GB', label: '2160p 4K [6.5GB]', url: 'https://example.com/dl32' },
    ],
    imdbRating: 7.2,
    isTrending: true,
    tags: ['Comedy', 'Fantasy'],
  },
  {
    title: 'Download Spy x Family Anime (2022) 720p [850MB] | 1080p [1.7GB]',
    cleanTitle: 'Spy x Family Anime',
    description: 'A spy, an assassin, and a psychic must pretend to be a normal family.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example16.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example16.jpg',
    releaseDate: new Date('2022-04-09'),
    releaseYear: 2022,
    source: 'WEB-DL',
    audioLanguages: ['Japanese', 'English'],
    type: 'anime',
    ottPlatform: 'netflix',
    genres: ['Animation', 'Comedy', 'Action'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '850MB', label: '720p [850MB]', url: 'https://example.com/dl33' },
      { quality: '1080p', size: '1.7GB', label: '1080p [1.7GB]', url: 'https://example.com/dl34' },
    ],
    imdbRating: 8.5,
    isTrending: true,
    tags: ['Anime', 'Comedy'],
  },
  {
    title: 'Download Guardians of the Galaxy Vol 3 (2023) BluRay 1080p [1.9GB] | 2160p 4K [6GB]',
    cleanTitle: 'Guardians of the Galaxy Vol 3',
    description: 'The final chapter of the Guardians\' story sees them face off against dangerous foes.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example17.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example17.jpg',
    releaseDate: new Date('2023-05-05'),
    releaseYear: 2023,
    source: 'BluRay',
    audioLanguages: ['English'],
    type: 'movie',
    ottPlatform: 'disney',
    genres: ['Action', 'Adventure', 'Comedy'],
    qualities: ['1080p', '2160p'],
    downloadLinks: [
      { quality: '1080p', size: '1.9GB', label: '1080p [1.9GB]', url: 'https://example.com/dl35' },
      { quality: '2160p', size: '6GB', label: '2160p 4K [6GB]', url: 'https://example.com/dl36' },
    ],
    imdbRating: 8.0,
    isTrending: true,
    tags: ['Action', 'Comedy'],
  },
  {
    title: 'Download Hello World Documentary (2024) 1080p [800MB]',
    cleanTitle: 'Hello World Documentary',
    description: 'A documentary exploring the impact of the internet on human civilization.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example18.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example18.jpg',
    releaseDate: new Date('2024-01-15'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'documentary',
    ottPlatform: 'netflix',
    genres: ['Documentary'],
    qualities: ['1080p'],
    downloadLinks: [
      { quality: '1080p', size: '800MB', label: '1080p [800MB]', url: 'https://example.com/dl37' },
    ],
    imdbRating: 7.6,
    tags: ['Documentary'],
  },
  {
    title: 'Download WWE WrestleMania 40 (2024) 720p [1.2GB] | 1080p [2.5GB]',
    cleanTitle: 'WWE WrestleMania 40',
    description: 'The greatest wrestling spectacle unfolds with epic matches and legendary moments.',
    posterUrl: 'https://image.tmdb.org/t/p/w342/example19.jpg',
    backdropUrl: 'https://image.tmdb.org/t/p/w1280/example19.jpg',
    releaseDate: new Date('2024-04-06'),
    releaseYear: 2024,
    source: 'WEB-DL',
    audioLanguages: ['English'],
    type: 'wwe',
    ottPlatform: 'wwe',
    genres: ['Sports'],
    qualities: ['720p', '1080p'],
    downloadLinks: [
      { quality: '720p', size: '1.2GB', label: '720p [1.2GB]', url: 'https://example.com/dl38' },
      { quality: '1080p', size: '2.5GB', label: '1080p [2.5GB]', url: 'https://example.com/dl39' },
    ],
    imdbRating: 7.9,
    tags: ['WWE', 'Sports'],
  },
];

const SITE_LINKS_ROW_1 = [
  {
    label: '🎬 RogMovies',
    url: 'https://rogmovies.com',
    color: '#22c55e',
    icon: '🎬',
    row: 1,
    order: 1,
  },
  {
    label: '🎬 GokuHD',
    url: 'https://gokuhd.com',
    color: '#06b6d4',
    icon: '🎬',
    row: 1,
    order: 2,
  },
  {
    label: '🎬 XprimeHub',
    url: 'https://xprimehub.com',
    color: '#f97316',
    icon: '🎬',
    row: 1,
    order: 3,
  },
  {
    label: '✈️ Join Telegram',
    url: 'https://t.me/vegamovies',
    color: '#3b82f6',
    icon: '✈️',
    row: 1,
    order: 4,
  },
];

const SITE_LINKS_ROW_2 = [
  {
    label: 'Anime',
    url: '/anime',
    color: '#3b82f6',
    row: 2,
    order: 1,
  },
  {
    label: 'Trending',
    url: '/trending',
    color: '#3b82f6',
    row: 2,
    order: 2,
  },
  {
    label: 'K-Drama',
    url: '/kdrama',
    color: '#3b82f6',
    row: 2,
    order: 3,
  },
  {
    label: 'AMZN Prime',
    url: '/ott/amazon',
    color: '#3b82f6',
    row: 2,
    order: 4,
  },
  {
    label: 'Netflix',
    url: '/ott/netflix',
    color: '#3b82f6',
    row: 2,
    order: 5,
  },
  {
    label: 'English',
    url: '/browse?audioLanguages=English',
    color: '#3b82f6',
    row: 2,
    order: 6,
  },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Movie.deleteMany({});
    await Admin.deleteMany({});
    await SiteLink.deleteMany({});

    console.log('Cleared existing data');

    const createdMovies = await Movie.insertMany(SAMPLE_MOVIES);
    console.log(`Created ${createdMovies.length} movies`);

    const admin = new Admin({
      username: 'admin',
      email: 'admin@vegamovies.com',
      passwordHash: 'admin123',
      role: 'admin',
    });
    await admin.save();
    console.log('Created admin user (username: admin, password: admin123)');

    await SiteLink.insertMany([...SITE_LINKS_ROW_1, ...SITE_LINKS_ROW_2]);
    console.log('Created site links');

    console.log('Seeding complete!');
    process.exit(0);
  } catch (error) {
    console.error('Seeding failed:', error.message);
    process.exit(1);
  }
}

seed();
